apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-hydrocalc

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - bot/deployment.yaml
  - istio/virtualservice.yaml
